version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_DATABASE=product
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product
    volumes:
      - user_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  user_data:
