apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # Set the desired NodePort here
  type: LoadBalancer # Use "NodePort" if you are running Kubernetes locally
