name: Docker Image CI

on:
  push:
    branches: [ "main" ]
      
jobs:        
  build-login-publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3
   
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: docker build -t darshanjain/flask-app:latest .
  
      - name: push latest image
        run: docker push darshanjain/flask-app:latest
        
      - name: tag image with version id
        run: docker image tag darshanjain/flask-app:latest darshanjain/flask-app:${{ github.sha }}
   
      - name: push with commit tag image
        run: docker push darshanjain/flask-app:${{ github.sha }}
